name = "Modpack"
author = "njeromin"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efdf50f42f679c8a71698fc003d798465ccf28c916accd279553f76fdc9f7b1c"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
