name = "Modpack"
author = "njeromin"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8cdcbf180078370f08e828ae2dbaae75ad4f01e6f98a08ed0d746ec21b9830b8"

[versions]
forge = "47.2.18"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
