name = "Modpack"
author = "njeromin"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc6814c575d092992856daa9672fb0615a60bedfa8da6cd4bdbb09af1d02ad2b"

[versions]
forge = "47.2.18"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
