name = "Modpack"
author = "njeromin"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3a168c889cb5b802fe6a155fc41684c6219dd3eb2dcdbe1620de9bc3d89cc14"

[versions]
forge = "47.2.18"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
