name = "Modpack"
author = "njeromin"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "088b0de2116975cd6d000b53506e4c428c75bf7b009acbfdf811a916c081521d"

[versions]
forge = "47.2.18"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
