name = "Modpack"
author = "njeromin"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33a611c13c176fc4fb63bfd1b38d1c854867a003f117d50c7c9ec08fe5181dfe"

[versions]
forge = "47.2.18"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
